#!/usr/bin/env python

import json

from os import environ, path

# Environment configurations
APP_KEY = environ.get('APP_KEY')
APP_KEY_FILE = '/BETA_KEY'

SETTINGS_FILE = path.join(path.expanduser('~'), '.MakeMKV/settings.conf')

settings = {}

if not APP_KEY:
    with open(APP_KEY_FILE, 'r') as fh:
        APP_KEY = fh.read().strip()

settings.update({
    'app_Key': APP_KEY,
})

with open(SETTINGS_FILE, 'w') as fh:
    for key, val in settings.items():
        fh.write('%s = "%s"' % (key, val))
